// Generated by CoffeeScript 1.9.3
var App, closeThemeBox, darkBooth, darkTheme, elp, generateDeftheme, getColor, getFaceList, lightTheme, masterKeys, removeTheme, saveCurrentTheme, saveToLocalStorage, setColor, setTheme, setUndoKey, setUndoLive, themeGenerator, themes, undo, undoTheme, updateUserThemes, userThemes;

generateDeftheme = function(name) {
  return $.get('./js/templates/deftheme.handlebars').then(function(t) {
    var compiled, o;
    o = _.extend({
      name: name
    }, App.liveTheme);
    compiled = Handlebars.compile(t);
    return compiled(o);
  });
};

themeGenerator = function() {
  var name;
  name = $('#theme-name').val();
  if (!name) {
    name = prompt("Generate theme", "untitled");
    $('#theme-name').val(name);
  }
  return generateDeftheme(name).then(function(generated) {
    App.generatedTheme = generated;
    App.generatedThemeName = name + "-theme.el";
    return $.get('./js/templates/deftheme-panel.handlebars', function(file) {
      var c, compiled, ctx;
      compiled = Handlebars.compile(file);
      ctx = {
        generated: generated,
        name: name
      };
      c = compiled(ctx);
      $('#theme-generated').html(c);
      return smoothScroll.animateScroll(null, '#theme-generated');
    });
  });
};

saveCurrentTheme = function() {
  var downloadLink, textBlob;
  if (!(App.generatedTheme && App.generatedThemeName)) {
    return;
  }
  textBlob = new Blob([App.generatedTheme], {
    type: 'text/plain'
  });
  downloadLink = document.createElement("a");
  downloadLink.download = App.generatedThemeName;
  if (window.webkitURL !== null) {
    downloadLink.href = window.webkitURL.createObjectURL(textBlob);
  } else {
    downloadLink.href = window.URL.createObjectURL(textBlob);
    downloadLink.onclick = function(e) {
      return document.body.removeChild(e.target);
    };
    downloadLink.style.display = "none";
    document.body.appendChild(downloadLink);
  }
  return downloadLink.click();
};

App = App || {};

App.codeSpans = {
  kw: '<span class="keyword">',
  cm: '<span class="comment">',
  bi: '<span class="builtin">',
  ty: '<span class="type">',
  va: '<span class="variable">',
  co: '<span class="constant">',
  st: '<span class="string">',
  fn: '<span class="function">',
  rg: '<span class="region">',
  ss: '<span class="secondary-selection">',
  cu: '<span class="cursor">',
  sx: '</span>'
};

App.faceTable = {
  background: {
    id: "rbg",
    title: "Background",
    rx: /background-color +\. +"([^"]*)"/,
    rx24: /default +\(\(t +\(\(t +\(.*:background +"([^"]*)"/,
    el: ['.default', 'background-color']
  },
  foreground: {
    id: "rfg",
    title: "Foreground",
    rx: /foreground-color \. +"([^"]*)"/,
    rx24: /default +\(\(t +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.default', 'color']
  },
  keyword: {
    id: "rkw",
    title: "Keywords",
    rx: /font-lock-keyword-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.keyword', 'color']
  },
  comment: {
    id: "rcmt",
    title: "Comments",
    rx: /font-lock-comment-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.comment', 'color']
  },
  builtin: {
    id: "rbt",
    title: "Builtins",
    rx: /font-lock-builtin-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.builtin', 'color']
  },
  type: {
    id: "rtp",
    title: "Class/Type",
    rx: /font-lock-type-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.type', 'color']
  },
  variable: {
    id: "rvar",
    title: "Variables",
    rx: /font-lock-variable-name-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.variable', 'color']
  },
  constant: {
    id: "rconst",
    title: "Constants",
    rx: /font-lock-constant-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.constant', 'color']
  },
  string: {
    id: "rstr",
    title: "Strings",
    rx: /font-lock-string-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.string', 'color']
  },
  "function": {
    id: "rfun",
    title: "Functions",
    rx: /font-lock-function-name-face +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.function', 'color']
  },
  cursor: {
    id: "rcr",
    title: "Cursor",
    rx: /cursor-color +\. +"([^"]*)"/,
    rx24: /cursor +\(\(t +\(\(t +\(.*:background +"([^"]*)"/,
    el: ['.cursor', 'background-color']
  },
  region: {
    id: "reg",
    title: "Region",
    rx: /region +\(\(t +\(.*:background +"([^"]*)"/,
    el: ['.region', 'background-color']
  },
  secondary: {
    id: "rss",
    title: "Secondary Selection",
    rx: /secondary-selection +\(\(t +\(.*:background +"([^"]*)"/,
    el: ['.secondary-selection', 'background-color']
  },
  border: {
    id: "rbd",
    title: "Fringe",
    rx: /border-color +\. +"([^"]*)"/,
    rx24: /fringe +\(\(t +\(\(t +\(.*:background +"([^"]*)"/,
    el: ['.fringe', 'border-color']
  },
  modelinebg: {
    id: "modbg",
    title: "Modeline bg",
    rx: /mode-line +\(\(t +\(.*:background +"([^"]*)"/,
    el: ['.modeline', 'background-color']
  },
  modelinefg: {
    id: "modfg",
    title: "Modeline fg",
    rx: /mode-line +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.modeline', 'color']
  },
  prompt: {
    id: "pmp",
    title: "Minibuffer",
    rx: /minibuffer-prompt +\(\(t +\(.*:foreground +"([^"]*)"/,
    el: ['.prompt', 'color']
  }
};

getFaceList = function(t) {
  return _.keys(t).map(function(k) {
    return {
      name: k,
      id: t[k].id,
      title: t[k].title
    };
  });
};

App = App || {};

App.liveTheme = {};

masterKeys = function() {
  return _.keys(App.faceTable);
};

elp = function(k) {
  return App.faceTable[k].el[1];
};

getColor = function(k) {
  return tinycolor($(App.faceTable[k].el[0]).css(elp(k))).toHexString();
};

setColor = function(k, col) {
  $(App.faceTable[k].el[0]).css(elp(k), col);
  $("input[name=" + k + "]").spectrum("set", col);
  $("input[name=" + k + "]").val(col);
  return App.liveTheme[k] = col;
};

setTheme = function(themeJson, name) {
  var o;
  if (name == null) {
    name = null;
  }
  if (!themeJson) {
    return;
  }
  o = JSON.parse(themeJson);
  _.each(_.keys(o), function(k) {
    return setColor(k, o[k]);
  });
  if (name) {
    return $('#theme-name').val(name);
  }
};

userThemes = {};

updateUserThemes = function() {
  $('#user-themes').empty();
  _.each(_.keys(userThemes), function(k) {
    return delete userThemes[k];
  });
  _.each(_.keys(localStorage), function(t) {
    if (localStorage.getItem(t)) {
      return userThemes[t] = localStorage.getItem(t);
    }
  });
  if (_.keys(userThemes).length > 0) {
    return $.get('./js/templates/user-themes.handlebars', function(file) {
      var template;
      template = Handlebars.compile(file);
      return $('#user-themes').html(template({
        userThemes: userThemes
      }));
    });
  }
};

saveToLocalStorage = function() {
  var name;
  name = $('#theme-name').val();
  if (!name) {
    name = prompt("Save theme", "untitled");
  }
  if (!name) {
    return;
  }
  $('#theme-name').val(name);
  if (localStorage.getItem(name)) {
    this.undoTheme = localStorage.getItem(name);
  }
  localStorage.setItem(name, JSON.stringify(App.liveTheme));
  return updateUserThemes();
};

removeTheme = function(name) {
  if (confirm("Remove theme " + name)) {
    if (localStorage.getItem(name)) {
      this.undoTheme = localStorage.getItem(name);
    }
    localStorage.removeItem(name);
    return updateUserThemes();
  }
};

undoTheme = {};

setUndoKey = function(k, v) {
  var undo;
  undo = JSON.parse(this.undoTheme);
  undo[k] = v;
  return this.undoTheme = JSON.stringify(undo);
};

setUndoLive = function() {
  return this.undoTheme = JSON.stringify(App.liveTheme);
};

undo = function() {
  setTheme(this.undoTheme);
  return setTheme(this.undoTheme);
};

closeThemeBox = function() {
  $('#theme-generated').hide();
  $('#theme-generated .msg').remove();
  return $('#generate').removeAttr('disabled');
};

$(function() {
  smoothScroll.init({
    speed: 500,
    easing: 'easeInCubic',
    updateURL: false,
    offset: 0
  });
  $('[data-toggle=tooltip]').tooltip({
    placement: 'top'
  });
  $.get('./js/templates/theme-selector.handlebars', function(file) {
    var template;
    template = Handlebars.compile(file);
    return $('#theme-selector').html(template({
      themes: themes
    }));
  });
  $.get('./js/templates/face-list.handlebars', function(file) {
    var list, template;
    template = Handlebars.compile(file);
    list = getFaceList(App.faceTable);
    $('#face-list').html(template(list));
    return $('input.els').spectrum({
      clickoutFiresChange: true,
      showInitial: true,
      showInput: true,
      preferredFormat: "hex",
      chooseText: "Set",
      cancelText: "Reset",
      change: function(color) {
        return console.log("Change event from spectrum", color);
      },
      move: function(color) {
        return setColor(this.name, color.toHexString());
      }
    });
  }).then(function() {
    return $.get('./js/templates/python.handlebars', function(file) {
      var template;
      template = Handlebars.compile(file);
      return $('#code-sample').html(template(App.codeSpans));
    }).then(function() {
      return setTheme(darkTheme);
    });
  });
  if (_.keys(localStorage).length > 0) {
    updateUserThemes();
  }
  return $(document).on('click', '#generate', themeGenerator);
});

lightTheme = "{\n  \"foreground\":  \"#242121\",\n  \"builtin\":     \"#738aa1\",\n  \"comment\":     \"#7d827d\",\n  \"keyword\":     \"#105163\",\n  \"variable\":    \"#ac8d4b\",\n  \"constant\":    \"#456b48\",\n  \"string\":      \"#4c7685\",\n  \"type\":        \"#659915\",\n  \"function\":    \"#375a0d\",\n  \"region\":      \"#cccccc\",\n  \"secondary\":   \"#cddbec\",\n  \"border\":      \"#eef0f0\",\n  \"background\":  \"#ffffff\",\n  \"modelinefg\":  \"#ffffff\",\n  \"modelinebg\":  \"#6f8784\",\n  \"cursor\":      \"#000000\",\n  \"prompt\":      \"#7299ff\"\n}";

darkTheme = "{\n  \"foreground\": \"#fdf4c1\",\n  \"builtin\":    \"#fe8019\",\n  \"comment\":    \"#7c6f64\",\n  \"keyword\":    \"#fb4934\",\n  \"variable\":   \"#83a598\",\n  \"constant\":   \"#d3869b\",\n  \"string\":     \"#b8bb26\",\n  \"type\":       \"#d3869b\",\n  \"function\":   \"#b8bb26\",\n  \"region\":     \"#504945\",\n  \"secondary\":  \"#3e3834\",\n  \"border\":     \"#282828\",\n  \"background\": \"#282828\",\n  \"modelinefg\": \"#282828\",\n  \"modelinebg\": \"#7c6f64\",\n  \"cursor\":     \"#fdf4c1\",\n  \"prompt\":     \"#b8bb26\"\n}";

darkBooth = "{\n  \"foreground\": \"#fdf4c1\",\n  \"builtin\":    \"#fe8019\",\n  \"comment\":    \"#7c6f64\",\n  \"keyword\":    \"#dd6f48\",\n  \"variable\":   \"#83a598\",\n  \"constant\":   \"#bbaa97\",\n  \"string\":     \"#429489\",\n  \"type\":       \"#66999d\",\n  \"function\":   \"#a99865\",\n  \"region\":     \"#504945\",\n  \"secondary\":  \"#3e3834\",\n  \"border\":     \"#282828\",\n  \"background\": \"#282828\",\n  \"modelinefg\": \"#ece09f\",\n  \"modelinebg\": \"#1e1c1a\",\n  \"cursor\":     \"#fdf4c1\",\n  \"prompt\":     \"#61acbb\"\n}";

themes = {
  "Dark": darkTheme,
  "Light": lightTheme,
  "DarkBooth": darkBooth
};
